name: GH Pages Deploy Workflow

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "16"
              
            - name: Install dependencies
              run: npm ci
            
            - name: Minify code
              run: npm run build

            - name: Deploy
              uses: crazy-max/ghaction-github-pages@v1
              with:
                target_branch: gh-pages
                build_dir: build
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}